[params]
about = "A Texas Sized Journey Into DevOps"
email = "thebeardgrammer@texops.io"
facebookid = "mattdreynolds"
githubid = "thebeardgrammer"
headerhostname = "texops.io"
headerusername = "thebeardgrammer"
linkedinid = "matthewdavidreynolds"
name = "Matt Reynolds"
profilepicture = "https://s3.amazonaws.com/texopsbackup/assets/img/logo.png"
twitterid = "thebeardgrammer"
