baseURL = "http://www.texops.io"
languageCode = "en-us"
title = "TexOps.io"
[[menu.header]]
name = "posts"
url = "/posts"
weight = 0
[[menu.header]]
name = "about"
url = "/about"
weight = 1
[params]
about = "A Texas Sized Journey Into DevOps"
email = "thebeardgrammer@texops.io"
facebookid = "mattdreynolds"
githubid = "thebeardgrammer"
headerhostname = "texops.io"
headerusername = "thebeardgrammer"
linkedinid = "matthewdavidreynolds"
name = "Matt Reynolds"
profilepicture = "https://s3.amazonaws.com/texopsbackup/assets/img/logo.png"
twitterid = "thebeardgrammer"
